name: Build and deploy Docker app to Lightsail
on:
  push:
    paths:
      - 'SERVER_Backend/**'

env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: iberiapp-final-try
  DOCKER_CONTAINER_NAME: final-backend-iberiapp
  working-directory: ./SERVER_Backend

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: sudo docker build -t ${{ env.DOCKER_CONTAINER_NAME }} .
        working-directory: ${{ env.working-directory }}
        #run: docker buildx build --platform=linux/amd64 -t ${{ env.DOCKER_CONTAINER_NAME }}:release .
      - name: Push and Deploy
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${{ env.DOCKER_CONTAINER_NAME }} \
            --image ${{ env.DOCKER_CONTAINER_NAME }}
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
          image_name = ${(cat image.txt)}
          aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json "{
            \"containers\": {
               \"flask\": {
                  \"image\": \"${image_name}\",
                  \"environment\": {\"DB_HOST\": \"${{ secrets.DB_HOST }}\", \"DB_USER\": \"${{ secrets.DB_USER }}\",
                              \"DB_PASS\": \"${{ secrets.DB_PASS }}\", \"DB_NAME\": \"${{ secrets.DB_NAME }}\"
                  \"ports\": {
                     \"3000\": \"HTTP\"
                  }
               }
            },
            \"publicEndpoint\": {
               \"containerName\": \"flask\",
               \"containerPort\": 3000
            }
          }"
